name: python-ci
on : push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: display python version and location
        run: |
         python --version
         which python
      - name: install dependencies
        run: |
         pip install ".[dev]"
      - name: checking black
        run: |
         black --check .
      - name: checking ruff
        run: |
         ruff check . 
      - name: checking mypy src
        run: |
         mypy src/
      - name: checking bandit
        run: |
         bandit -c pyproject.toml -r .
  release:
    runs-on: ubuntu-latest
    needs: 
      - build-and-test
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dep
        run: |
         pip install python-semantic-release
      - name: create relase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         semantic-release version
         semantic-release publish


  