name: python-ci
on : push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: display python version and location
        run: |
         python --version
         which python
      - name: install dependencies
        run: |
         pip install ".[dev]"
      - name: checking black
        run: |
         black --check .
      - name: checking ruff
        run: |
         ruff check . 


  